// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwIcdlU2sZrTimLwam_GSjT06-5chFgTg',
    appId: '1:793154239105:web:4efae305fc8e0365eeab80',
    messagingSenderId: '793154239105',
    projectId: 'crud-pumasunam',
    authDomain: 'crud-pumasunam.firebaseapp.com',
    storageBucket: 'crud-pumasunam.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDEUA2RvFCiZrXhpmLLc2_5LY0lA8dNyw',
    appId: '1:793154239105:android:e30b2f943d5cb458eeab80',
    messagingSenderId: '793154239105',
    projectId: 'crud-pumasunam',
    storageBucket: 'crud-pumasunam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvBaaAdND5sG4EaQZ3NP0VURMbLounOlQ',
    appId: '1:793154239105:ios:e1c84b884853e473eeab80',
    messagingSenderId: '793154239105',
    projectId: 'crud-pumasunam',
    storageBucket: 'crud-pumasunam.appspot.com',
    iosClientId: '793154239105-ugpqumqlmdr5fdc6jrtj1in5gsea8p15.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvBaaAdND5sG4EaQZ3NP0VURMbLounOlQ',
    appId: '1:793154239105:ios:e1c84b884853e473eeab80',
    messagingSenderId: '793154239105',
    projectId: 'crud-pumasunam',
    storageBucket: 'crud-pumasunam.appspot.com',
    iosClientId: '793154239105-ugpqumqlmdr5fdc6jrtj1in5gsea8p15.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud',
  );
}
